config/routes.rb
Rails.application.routes.draw do
  #get 'public_meets/new'

  # get 'public_posts/index'
  root 'public_posts#index'

  #get 'public_posts/show'

  #get 'public_posts/posts_category'

  get 'citas', to: 'public_meets#new', as: 'citas'
  get 'categorias/:id', to: 'public_posts#posts_category', as: 'posts_category'
  get 'articluos/:url', to: 'public_posts#show', as: 'posts_show'

  post 'create_meet', to: 'public_meets#create_meet', as: 'create_meet'
  post 'create_comment', to: 'public_posts#create_comment', as: 'create_comment'

  devise_for :users
  resources :meets
  resources :ads
  resources :comments
  resources :categories
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/meet.rb
class Meet < ApplicationRecord
end

app/controllers/meets_controller.rb
class MeetsController < ApplicationController
  before_action :set_meet, only: [:show, :edit, :update, :destroy]

  # GET /meets
  # GET /meets.json
  def index
    @meets = Meet.all
  end

  # GET /meets/1
  # GET /meets/1.json
  def show
  end

  # GET /meets/new
  def new
    @meet = Meet.new
  end

  # GET /meets/1/edit
  def edit
  end

  # POST /meets
  # POST /meets.json
  def create
    @meet = Meet.new(meet_params)

    respond_to do |format|
      if @meet.save
        format.html { redirect_to @meet, notice: 'Meet was successfully created.' }
        format.json { render :show, status: :created, location: @meet }
      else
        format.html { render :new }
        format.json { render json: @meet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meets/1
  # PATCH/PUT /meets/1.json
  def update
    respond_to do |format|
      if @meet.update(meet_params)
        format.html { redirect_to @meet, notice: 'Meet was successfully updated.' }
        format.json { render :show, status: :ok, location: @meet }
      else
        format.html { render :edit }
        format.json { render json: @meet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meets/1
  # DELETE /meets/1.json
  def destroy
    @meet.destroy
    respond_to do |format|
      format.html { redirect_to meets_url, notice: 'Meet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meet
      @meet = Meet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meet_params
      params.require(:meet).permit(:name, :meeting, :subject, :status)
    end
end

app/helpers/meets_helper.rb
module MeetsHelper
end

app/views/meets/_form.html.erb
<%= form_with(model: meet, local: true) do |form| %>
  <% if meet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meet.errors.count, "error") %> prohibited this meet from being saved:</h2>

      <ul>
      <% meet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :meet_name, class: 'form-control'%>
  </div>

  <div class="field">
    <%= form.label :meeting %>
    <%= form.date_select :meeting, id: :meet_meeting, class: 'form-control'%>
  </div>

  <div class="field">
    <%= form.label :subject %>
    <%= form.text_area :subject, id: :meet_subject, class: 'form-control'%>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status, id: :meet_status, class: 'form-control'%>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-default'%>
  </div>
<% end %>

app/views/meets/edit.html.erb
<h1>Editing Meet</h1>

<%= render 'form', meet: @meet %>

<%= link_to 'Show', @meet %> |
<%= link_to 'Back', meets_path %>

app/views/meets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Citas</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Citar</th>
      <th>Asunto</th>
      <th>Estatus</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meets.each do |meet| %>
      <tr>
        <td><%= meet.name %></td>
        <td><%= meet.meeting %></td>
        <td><%= meet.subject %></td>
        <td><%= meet.status %></td>
        <td><%= link_to 'Ver', meet, class: 'btn btn-default'%></td>
        <td><%= link_to 'Editar', edit_meet_path(meet), class: 'btn btn-default'%></td>
        <td><%= link_to 'Eliminar', meet, method: :delete, data: { confirm: 'Desea Eliminarlo?' }, class: 'btn btn-default' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Crear Cita', new_meet_path %>

app/views/meets/new.html.erb
<h1>Neva Cita</h1>

<%= render 'form', meet: @meet %>

<%= link_to 'Volver', meets_path %>

app/views/meets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @meet.name %>
</p>

<p>
  <strong>Citas:</strong>
  <%= @meet.meeting %>
</p>

<p>
  <strong>Asunto:</strong>
  <%= @meet.subject %>
</p>

<p>
  <strong>Estatus:</strong>
  <%= @meet.status %>
</p>

<%= link_to 'Editar', edit_meet_path(@meet) %> |
<%= link_to 'Volver', meets_path %>