config/routes.rb
Rails.application.routes.draw do
  #get 'public_meets/new'

  # get 'public_posts/index'
  root 'public_posts#index'

  #get 'public_posts/show'

  #get 'public_posts/posts_category'

  get 'citas', to: 'public_meets#new', as: 'citas'
  get 'categorias/:id', to: 'public_posts#posts_category', as: 'posts_category'
  get 'articluos/:url', to: 'public_posts#show', as: 'posts_show'

  post 'create_meet', to: 'public_meets#create_meet', as: 'create_meet'
  post 'create_comment', to: 'public_posts#create_comment', as: 'create_comment'

  devise_for :users
  resources :meets
  resources :ads
  resources :comments
  resources :categories
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  belongs_to :category
  belongs_to :user

  scope :publisheds, -> {where status: true}
  scope :orden, -> {order name}


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :status, :url, :user_id, :category_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :title, id: :post_title, class: 'form-control'%>
  </div>

  <div class="field">
    <%= form.label :contenido %>
    <%= form.text_area :content, id: :post_content, class: 'form-control'%>
  </div>

  <div class="field">
    <%= form.label :estatus %>
    <%= form.check_box :status, id: :post_status, class: 'form-control'%>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :post_url, class: 'form-control'%>
  </div>

    <div class="field">
      <%= form.label :categoria %>
      <%= form.select :category_id, list_categories.collect {|c| [c.name, c.id]} %>
    </div>

    <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="actions">
    <%= form.submit class: 'btn btn-default'%>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editar Articulo</h1>

<%= render 'form', post: @post %>

<%= link_to 'Ver', @post %> |
<%= link_to 'Volver', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articulos</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Titulos</th>
      <th>Contenido</th>
      <th>Estatus</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.status %></td>
        <td><%= post.url %></td>
        <td><%= link_to 'Ver', post, class: 'btn btn-default' %></td>
        <td><%= link_to 'Editar', edit_post_path(post), class: 'btn btn-default' %></td>
        <td><%= link_to 'Eliminar', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Crear Articulo', new_post_path %>

app/views/posts/new.html.erb
<h1>Nuevo Articulo</h1>

<%= render 'form', post: @post %>

<%= link_to 'Volver', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Contenido:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Estatus:</strong>
  <%= @post.status %>
</p>

<p>
  <strong>Url:</strong>
  <%= @post.url %>
</p>

<%= link_to 'Editar', edit_post_path(@post) %> |
<%= link_to 'Volver', posts_path %>