config/routes.rb
Rails.application.routes.draw do
  #get 'public_meets/new'

  # get 'public_posts/index'
  root 'public_posts#index'

  #get 'public_posts/show'

  #get 'public_posts/posts_category'

  get 'citas', to: 'public_meets#new', as: 'citas'
  get 'categorias/:id', to: 'public_posts#posts_category', as: 'posts_category'
  get 'articluos/:url', to: 'public_posts#show', as: 'posts_show'

  post 'create_meet', to: 'public_meets#create_meet', as: 'create_meet'
  post 'create_comment', to: 'public_posts#create_comment', as: 'create_comment'

  devise_for :users
  resources :meets
  resources :ads
  resources :comments
  resources :categories
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :name, id: :category_name, class: 'form-control'%>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-default'%>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editar Categoria</h1>

<%= render 'form', category: @category %>

<%= link_to 'Ver', @category %> |
<%= link_to 'Volver', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categorias</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'ver', category, class: 'btn btn-default' %></td>
        <td><%= link_to 'Editar', edit_category_path(category), class: 'btn btn-default' %></td>
        <td><%= link_to 'Eliminar', category, method: :delete, data: { confirm: 'Desea Eliminarlo?' }, class: 'btn btn-default' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Crear Categoria', new_category_path %>

app/views/categories/new.html.erb
<h1>Nueva Categoria</h1>

<%= render 'form', category: @category %>

<%= link_to 'Volver', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Editar', edit_category_path(@category) %> |
<%= link_to 'Volver', categories_path %>