config/routes.rb
Rails.application.routes.draw do
  #get 'public_meets/new'

  # get 'public_posts/index'
  root 'public_posts#index'

  #get 'public_posts/show'

  #get 'public_posts/posts_category'

  get 'citas', to: 'public_meets#new', as: 'citas'
  get 'categorias/:id', to: 'public_posts#posts_category', as: 'posts_category'
  get 'articluos/:url', to: 'public_posts#show', as: 'posts_show'

  post 'create_meet', to: 'public_meets#create_meet', as: 'create_meet'
  post 'create_comment', to: 'public_posts#create_comment', as: 'create_comment'

  devise_for :users
  resources :meets
  resources :ads
  resources :comments
  resources :categories
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Blog" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>



    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top barra-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#"> <strong>Blog de Rails</strong> - <small> Administración </small></a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h4> <small>Usuarios <%= current_user.email %></small></h4>
            <h3>Menu</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Menu</li>
              <li><%= link_to "Articulos", posts_path  %></li>
              <li><%= link_to "Categorias", categories_path  %></li>
              <li><%= link_to "Comentarios", comments_path  %></li>
              <li><%= link_to "Anuncios", ads_path  %></li>
              <li><%= link_to "Citas", meets_path  %></li>
              <li><%= link_to "Salir", destroy_user_session_path, method: :delete%></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <hr/>
        <p>&copy; Company 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Blog" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top barras-top">
      <div class="container">
        <div class="row">
          <div class="col-md-9">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <div class="navbar-collapse collapse navbar-responsive-collapse">
              <ul class="nav navbar-nav blanco-top">
                <li><%= link_to "Arrticulos", root_path  %></li>
                <li><%= link_to "Citas", citas_path  %></li>
              </ul>
            </div>
          </div>
          <div class="col-md-3">
            <div class="navbar-collapse collapse navbar-responsive-collapse">
              <ul class="nav navbar-nav blanco-top">
                <% if user_signed_in? %>
                    <li> <%= link_to "Panel", posts_path %></li>
                    <li> <a>Hola <%= current_user.email %></a></li>
                <% else %>
                    <li><%= link_to "Acceder", new_user_session_path  %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-12 tituloBlog">
      <h1>El Blog de rails</h1>
      <h3>Todo sobre Ruby on rails en el blog más completo</h3>
    </div>

    <div class="container ">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav col-md-12 bordeo-top">
            <h3>Opciones</h3>
          </div><!--/.well -->
            <div class="well sidebar-nav bordeo-top">
              <ul class="nav nav-list">
                <li class="nav-header">Categorias</li>
                <% list_categories.each do |l|  %>
                    <li><%= link_to l.name, posts_category_path(l.id) %></li>
                <% end %>
              </ul>
            </div>
            <div class="anuncio">
              <%= link_to ad_available.link, target: '_blank' do %>
                <%= image_tag ad_available.image, width: 330 %>
              <% end %>
            </div>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <hr/>
        <p>&copy; Company 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>